---
  - name: update and upgrade packages
    apt:
      upgrade: yes
      update_cache: yes

  - name: install additional software
    apt:
      name: tree
      state: present

# tasks file for update_host
